issueTrackerURL = "${repo_page_url}/issues"
license = "${mod_license}"
loaderVersion = "${neoforge_loader_version_range}"
modLoader = "javafml"

[[mods]]
authors = "Sora Tonami"
description = '''${mod_description}'''
displayName = "${mod_name}"
logoFile = "assets/${mod_id}/logo.png"
modId = "${mod_id}"
updateJSONURL = "${update_json_url}"
version = "${mod_version}"

[[dependencies.${ mod_id }]]
mandatory = true
modId = "architectury"
ordering = "AFTER"
side = "BOTH"
versionRange = "${architectury_version_range}"

[[dependencies.${ mod_id }]]
mandatory = true
modId = "cloth_config"
ordering = "AFTER"
side = "CLIENT"
versionRange = "${cloth_config_version_range}"

[[dependencies.${ mod_id }]]
mandatory = true
modId = "forge"
ordering = "AFTER"
side = "BOTH"
versionRange = "${neoforge_version_range}"

[[dependencies.${ mod_id }]]
mandatory = true
modId = "minecraft"
ordering = "AFTER"
side = "BOTH"
versionRange = "${minecraft_version_range}"
