name: Gradle Error Checker
on:
    pull_request:
        branches:
            - 1.20.1
    push:
        branches:
            - 1.20.1
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            -   name: Checkout
                uses: actions/checkout@v4
                with:
                    fetch-depth: 0
            -   name: Check for errors
                uses: github/super-linter@v5
                env:
                    VALIDATE_ALL_CODEBASE: false
